//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryHistory
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool EntryType { get; set; }
    
        public virtual Staff Staff { get; set; }

        public string EntryTypeTxt 
        {
            get { return EntryType == true ? "Успешно" : "Неуспешно"; }
        }
    }
}
