//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igora
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOfEquipment
    {
        public int Id { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public int EquipmentId { get; set; }
        public int Qty { get; set; }
        public int StaffId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
